export { LoginPage } from './login'
export { RegisterPage } from './register'
export { DashboardPage } from './dashboard'
export { ChatPage } from './chat'
export { HistoryPage } from './history'
export { ProfilePage } from './profile'
export { SettingsPage } from './settings'
export { AuthCallbackPage } from './auth-callback'
export { default as BotsPage } from './bots'
export { default as CollectionsPage } from './collections'
export { default as CollectionDetailPage } from './collection-detail'
export { default as BotConversationsPage } from './bot-conversations'
export { default as QuizzesPage } from './quizzes'
export { default as QuizTakePage } from './quiz-take'
export { default as QuizResultsPage } from './quiz-results'
export { default as TemplatesPage } from './templates'
export { default as AnalyticsPage } from './analytics'
